-- 코드를 입력하세요
SELECT C.AUTHOR_ID, C.AUTHOR_NAME, C.CATEGORY, SUM(C.SUM_SALES) AS TOTAL_SALES
FROM (
SELECT A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM(BS.SALES) * B.PRICE AS SUM_SALES, B.PRICE
FROM BOOK_SALES BS, BOOK B, AUTHOR A
WHERE BS.BOOK_ID = B.BOOK_ID AND B.AUTHOR_ID = A.AUTHOR_ID AND BS.SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
GROUP BY A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, B.PRICE) C
GROUP BY C.AUTHOR_ID, C.AUTHOR_NAME, C.CATEGORY
ORDER BY C.AUTHOR_ID ASC, C.CATEGORY DESC
