/* FIRST HALF: 상반기 주문 정보 / JULY: 7월 아이스크림 주문량 */
SELECT A.FLAVOR
FROM (
SELECT FLAVOR, SUM(TOTAL_ORDER) AS JULY_SUM
FROM JULY
GROUP BY FLAVOR ) A JOIN FIRST_HALF B ON A.FLAVOR = B.FLAVOR
ORDER BY (A.JULY_SUM + B.TOTAL_ORDER) DESC
LIMIT 3